# Create a new user
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "smith@mail.ru",
  "login": "smith",
  "password": "1qaz!QAZ"
}

###

# Get user by ID
GET http://localhost:3000/api/auth/e149361d-bcdb-422b-a7a5-96e94b1463c5 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlMTQ5MzYxZC1iY2RiLTQyMmItYTdhNS05NmU5NGIxNDYzYzUiLCJlbWFpbCI6InNtaXRoQG1haWwucnUiLCJsb2dpbiI6InNtaXRoIiwiaWF0IjoxNzQ5NjMwNjg3LCJleHAiOjE3NDk2MzA5ODd9.vMwl0TAan0jsiit-pcGvNEqC1Q02D4jwCfvrag693uY

###

# Login user by email and password
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "smith@mail.ru",
  "password": "1qaz!QAZ"
}

###
