### Create comment
POST http://localhost:3001/api/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkNDM4NzFhZC04OTgxLTRiZWEtYTIyNi02NDBjNGM2MTFjM2UiLCJlbWFpbCI6InRlc3RhdmF0YXIyMjJAbWFpbC5ydSIsImxvZ2luIjoiYXZhdGFydXNlcjIyMiIsImlhdCI6MTc1MDc3Mzg1NiwiZXhwIjoxNzUwNzc0MTU2fQ.msVd-Rmuj5HYjEW3u26sxV61odILSrqeB68_PGictq8

{
  "postId": "a673fe98-bbc9-442e-a3dd-d546b7e721cf",
  "text": "Отличный пост! Спасибо за информацию."
}

### Delete comment
DELETE http://localhost:3001/api/comments/11faa0a1-11f8-456f-8250-42189c8edc1a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlMTQ5MzYxZC1iY2RiLTQyMmItYTdhNS05NmU5NGIxNDYzYzUiLCJlbWFpbCI6InNtaXRoQG1haWwucnUiLCJsb2dpbiI6InNtaXRoIiwiaWF0IjoxNzQ5NjYxMzg0LCJleHAiOjE3NDk2NjE2ODR9.vdwl3C68JqPMvBZpUDn9J_L_R0O3RQ7yc8vI0TLEXsM

### Get comments by post
GET http://localhost:3001/api/comments/post/a673fe98-bbc9-442e-a3dd-d546b7e721cf
